version: '3.2'
services:
  geoserver-node:
    container_name: geoserver-node
    build: geoserver-docker
    ports:
      - 8080:8080
    networks:
      - api_stac_nw
    command: ['5g']
    tty: true

  stac-manager:
    container_name: stac-manager
    build: geoserver-docker
    ports:
      - 8888:8888
    volumes:
      - /mnt/geoserver_data:/usr/local/geoserver/data_dir
    networks:
      - api_stac_nw
    command: ['api.salo.ai', '8888', 'maps.salo.ai', '8080', '4g']
    tty: true
    depends_on:
      - geoserver-node

  nginx:
    image: "nginx:1.13.5"
    container_name: "nginx"
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx_configurations/stac_api_nginx_conf:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - api_stac_nw
    depends_on:
      - stac-manager

networks:
  api_stac_nw:
    driver: bridge
