version: '3.6'

services:
  geoserver:
    container_name: geoserver
    build: docker_contexts/geoserver_node_docker
    ports:
      - 8080:8080
    networks:
      - api_stac_nw
    volumes:
      - ${GEOSERVER_DATA_DIR}:${GEOSERVER_DATA_DIR}
    environment:
      - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
      - GEOSERVER_MAX_RAM=${GEOSERVER_MAX_RAM}
    tty: true

  stac_manager:
    container_name: stac_manager
    build: docker_contexts/stac-api-docker
    entrypoint: ["bash",  "-i", "/usr/local/stac_manager/start_stac_api.sh"]
    ports:
      - ${API_HOST_PORT}:${API_HOST_PORT}
    volumes:
      - ${GEOSERVER_DATA_DIR}:${GEOSERVER_DATA_DIR}
    image: stac_manager
    networks:
      - api_stac_nw
    tty: true
    depends_on:
      - geoserver
      - db
    environment:
      - BUCKET_READ_SERVICE_ACCOUNT_KEYFILE=/run/secrets/bucket_read_service_account_key
      - SIGN_URL_PUBLIC_KEY_PATH=/run/secrets/sign_url_public_key
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
      - API_HOST_PORT=${API_HOST_PORT}
      - FLASK_APP=stac_api
    secrets:
      - bucket_read_service_account_key
      - sign_url_public_key

  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql
    networks:
      - api_stac_nw

  expand_drive_service:
    container_name: expand_drive_service
    build: docker_contexts/expand_drive_service
    restart: always
    networks:
      - api_stac_nw
    devices:
      - ${DISK_RESIZE_SERVICE_DEVICE_NAME}:${DISK_RESIZE_SERVICE_DEVICE_NAME}
    command: [
      '--app_port', '${DISK_RESIZE_SERVICE_PORT}',
      '--disk_name', '${DISK_RESIZE_SERVICE_DISK_NAME}',
      '--device_name', '${DISK_RESIZE_SERVICE_DEVICE_NAME}',
      '--zone', '${DISK_RESIZE_SERVICE_ZONE}',
      '--max_size_gb', '${DISK_RESIZE_SERVICE_MAX_SIZE_GB}',
      ]
    environment:
      - DISK_RESIZE_SERVICE_ACCOUNT_KEYFILE=/run/secrets/disk_resize_service_account_key
    secrets:
      - disk_resize_service_account_key

  nginx:
    image: "nginx:1.13.5"
    container_name: "nginx"
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx_configurations/stac_api_nginx_conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - api_stac_nw
    depends_on:
      - stac_manager

networks:
  api_stac_nw:
    driver: bridge

secrets:
  disk_resize_service_account_key:
    file: ${DISK_RESIZE_SERVICE_ACCOUNT_KEYFILE}
  bucket_read_service_account_key:
    file: ${BUCKET_READ_SERVICE_ACCOUNT_KEYFILE}
  sign_url_public_key:
    file: ${SIGN_URL_PUBLIC_KEYFILE}
