version: '3.2'
services:
  geoserver-node:
    container_name: geoserver-node
    build: geoserver-docker
    ports:
      - 8080:8080
    networks:
      - web_nw
    command: ['5g']
    tty: true

  nginx:
    image: "nginx:1.13.5"
    container_name: "nginx"
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./geoserver_node_nginx_conf.d:/etc/nginx/conf.d
    networks:
      - web_nw

networks:
  web_nw:
    driver: bridge
