version: '3.6'

services:
  stac_manager_shell:
    container_name: stac_manager_shell
    build: docker_contexts/stac-api-docker
    entrypoint: ["bash"]
    working_dir: /usr/local/stac-api-docker
    volumes:
      - ./docker_contexts/stac-api-docker:/usr/local/stac-api-docker
    image: stac_manager_shell
    tty: true
    stdin_open: true
    depends_on:
      - test_db
      - pgadmin
    networks:
      - stac_shell_nw
    environment:
      - FLASK_APP=stac_api
      - SQLALCHEMY_DATABASE_URI=postgresql://db_test_user:db_test_password@test_db

  test_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: db_test_password
      POSTGRES_USER: db_test_user
    networks:
      - stac_shell_nw

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.localhost
      PGADMIN_DEFAULT_PASSWORD: db_test_password
      PGADMIN_LISTEN_PORT: 80
    depends_on:
      - test_db
    networks:
      - stac_shell_nw
    ports:
      - 8080:80

networks:
  stac_shell_nw:
    driver: bridge
