# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.fields import Fields
from openapi_server import util

from openapi_server.models.fields import Fields  # noqa: E501

class FieldsFilter(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, fields=None):  # noqa: E501
        """FieldsFilter - a model defined in OpenAPI

        :param fields: The fields of this FieldsFilter.  # noqa: E501
        :type fields: Fields
        """
        self.openapi_types = {
            'fields': Fields
        }

        self.attribute_map = {
            'fields': 'fields'
        }

        self._fields = fields

    @classmethod
    def from_dict(cls, dikt) -> 'FieldsFilter':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The fieldsFilter of this FieldsFilter.  # noqa: E501
        :rtype: FieldsFilter
        """
        return util.deserialize_model(dikt, cls)

    @property
    def fields(self):
        """Gets the fields of this FieldsFilter.


        :return: The fields of this FieldsFilter.
        :rtype: Fields
        """
        return self._fields

    @fields.setter
    def fields(self, fields):
        """Sets the fields of this FieldsFilter.


        :param fields: The fields of this FieldsFilter.
        :type fields: Fields
        """

        self._fields = fields
