# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Fields(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, include=None, exclude=None):  # noqa: E501
        """Fields - a model defined in OpenAPI

        :param include: The include of this Fields.  # noqa: E501
        :type include: List[str]
        :param exclude: The exclude of this Fields.  # noqa: E501
        :type exclude: List[str]
        """
        self.openapi_types = {
            'include': List[str],
            'exclude': List[str]
        }

        self.attribute_map = {
            'include': 'include',
            'exclude': 'exclude'
        }

        self._include = include
        self._exclude = exclude

    @classmethod
    def from_dict(cls, dikt) -> 'Fields':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The fields of this Fields.  # noqa: E501
        :rtype: Fields
        """
        return util.deserialize_model(dikt, cls)

    @property
    def include(self):
        """Gets the include of this Fields.


        :return: The include of this Fields.
        :rtype: List[str]
        """
        return self._include

    @include.setter
    def include(self, include):
        """Sets the include of this Fields.


        :param include: The include of this Fields.
        :type include: List[str]
        """

        self._include = include

    @property
    def exclude(self):
        """Gets the exclude of this Fields.


        :return: The exclude of this Fields.
        :rtype: List[str]
        """
        return self._exclude

    @exclude.setter
    def exclude(self, exclude):
        """Sets the exclude of this Fields.


        :param exclude: The exclude of this Fields.
        :type exclude: List[str]
        """

        self._exclude = exclude
