# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class GeoJSONPolygon(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, coordinates=None, bbox=None):  # noqa: E501
        """GeoJSONPolygon - a model defined in OpenAPI

        :param type: The type of this GeoJSONPolygon.  # noqa: E501
        :type type: str
        :param coordinates: The coordinates of this GeoJSONPolygon.  # noqa: E501
        :type coordinates: List[List[List[float]]]
        :param bbox: The bbox of this GeoJSONPolygon.  # noqa: E501
        :type bbox: List[float]
        """
        self.openapi_types = {
            'type': str,
            'coordinates': List[List[List[float]]],
            'bbox': List[float]
        }

        self.attribute_map = {
            'type': 'type',
            'coordinates': 'coordinates',
            'bbox': 'bbox'
        }

        self._type = type
        self._coordinates = coordinates
        self._bbox = bbox

    @classmethod
    def from_dict(cls, dikt) -> 'GeoJSONPolygon':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GeoJSON_Polygon of this GeoJSONPolygon.  # noqa: E501
        :rtype: GeoJSONPolygon
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self):
        """Gets the type of this GeoJSONPolygon.


        :return: The type of this GeoJSONPolygon.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this GeoJSONPolygon.


        :param type: The type of this GeoJSONPolygon.
        :type type: str
        """
        allowed_values = ["Polygon"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def coordinates(self):
        """Gets the coordinates of this GeoJSONPolygon.


        :return: The coordinates of this GeoJSONPolygon.
        :rtype: List[List[List[float]]]
        """
        return self._coordinates

    @coordinates.setter
    def coordinates(self, coordinates):
        """Sets the coordinates of this GeoJSONPolygon.


        :param coordinates: The coordinates of this GeoJSONPolygon.
        :type coordinates: List[List[List[float]]]
        """
        if coordinates is None:
            raise ValueError("Invalid value for `coordinates`, must not be `None`")  # noqa: E501

        self._coordinates = coordinates

    @property
    def bbox(self):
        """Gets the bbox of this GeoJSONPolygon.


        :return: The bbox of this GeoJSONPolygon.
        :rtype: List[float]
        """
        return self._bbox

    @bbox.setter
    def bbox(self, bbox):
        """Sets the bbox of this GeoJSONPolygon.


        :param bbox: The bbox of this GeoJSONPolygon.
        :type bbox: List[float]
        """

        self._bbox = bbox
