# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.geometrycollection_geo_json import GeometrycollectionGeoJSON
from openapi_server.models.linestring_geo_json import LinestringGeoJSON
from openapi_server.models.multilinestring_geo_json import MultilinestringGeoJSON
from openapi_server.models.multipoint_geo_json import MultipointGeoJSON
from openapi_server.models.multipolygon_geo_json import MultipolygonGeoJSON
from openapi_server.models.point_geo_json import PointGeoJSON
from openapi_server.models.polygon_geo_json import PolygonGeoJSON
from openapi_server import util

from openapi_server.models.geometrycollection_geo_json import GeometrycollectionGeoJSON  # noqa: E501
from openapi_server.models.linestring_geo_json import LinestringGeoJSON  # noqa: E501
from openapi_server.models.multilinestring_geo_json import MultilinestringGeoJSON  # noqa: E501
from openapi_server.models.multipoint_geo_json import MultipointGeoJSON  # noqa: E501
from openapi_server.models.multipolygon_geo_json import MultipolygonGeoJSON  # noqa: E501
from openapi_server.models.point_geo_json import PointGeoJSON  # noqa: E501
from openapi_server.models.polygon_geo_json import PolygonGeoJSON  # noqa: E501

class GeometryGeoJSON(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, coordinates=None, geometries=None):  # noqa: E501
        """GeometryGeoJSON - a model defined in OpenAPI

        :param type: The type of this GeometryGeoJSON.  # noqa: E501
        :type type: str
        :param coordinates: The coordinates of this GeometryGeoJSON.  # noqa: E501
        :type coordinates: List[List[List[List[float]]]]
        :param geometries: The geometries of this GeometryGeoJSON.  # noqa: E501
        :type geometries: List[GeometryGeoJSON]
        """
        self.openapi_types = {
            'type': str,
            'coordinates': List[List[List[List[float]]]],
            'geometries': List[GeometryGeoJSON]
        }

        self.attribute_map = {
            'type': 'type',
            'coordinates': 'coordinates',
            'geometries': 'geometries'
        }

        self._type = type
        self._coordinates = coordinates
        self._geometries = geometries

    @classmethod
    def from_dict(cls, dikt) -> 'GeometryGeoJSON':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The geometryGeoJSON of this GeometryGeoJSON.  # noqa: E501
        :rtype: GeometryGeoJSON
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self):
        """Gets the type of this GeometryGeoJSON.


        :return: The type of this GeometryGeoJSON.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this GeometryGeoJSON.


        :param type: The type of this GeometryGeoJSON.
        :type type: str
        """
        allowed_values = ["GeometryCollection"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def coordinates(self):
        """Gets the coordinates of this GeometryGeoJSON.


        :return: The coordinates of this GeometryGeoJSON.
        :rtype: List[List[List[List[float]]]]
        """
        return self._coordinates

    @coordinates.setter
    def coordinates(self, coordinates):
        """Sets the coordinates of this GeometryGeoJSON.


        :param coordinates: The coordinates of this GeometryGeoJSON.
        :type coordinates: List[List[List[List[float]]]]
        """
        if coordinates is None:
            raise ValueError("Invalid value for `coordinates`, must not be `None`")  # noqa: E501

        self._coordinates = coordinates

    @property
    def geometries(self):
        """Gets the geometries of this GeometryGeoJSON.


        :return: The geometries of this GeometryGeoJSON.
        :rtype: List[GeometryGeoJSON]
        """
        return self._geometries

    @geometries.setter
    def geometries(self, geometries):
        """Sets the geometries of this GeometryGeoJSON.


        :param geometries: The geometries of this GeometryGeoJSON.
        :type geometries: List[GeometryGeoJSON]
        """
        if geometries is None:
            raise ValueError("Invalid value for `geometries`, must not be `None`")  # noqa: E501

        self._geometries = geometries
