# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class IdsFilter(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, ids=None):  # noqa: E501
        """IdsFilter - a model defined in OpenAPI

        :param ids: The ids of this IdsFilter.  # noqa: E501
        :type ids: List[str]
        """
        self.openapi_types = {
            'ids': List[str]
        }

        self.attribute_map = {
            'ids': 'ids'
        }

        self._ids = ids

    @classmethod
    def from_dict(cls, dikt) -> 'IdsFilter':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The idsFilter of this IdsFilter.  # noqa: E501
        :rtype: IdsFilter
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ids(self):
        """Gets the ids of this IdsFilter.

        Array of Item ids to return. All other filter parameters that further restrict the number of search results are ignored  # noqa: E501

        :return: The ids of this IdsFilter.
        :rtype: List[str]
        """
        return self._ids

    @ids.setter
    def ids(self, ids):
        """Sets the ids of this IdsFilter.

        Array of Item ids to return. All other filter parameters that further restrict the number of search results are ignored  # noqa: E501

        :param ids: The ids of this IdsFilter.
        :type ids: List[str]
        """

        self._ids = ids
