# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class LinestringGeoJSON(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, coordinates=None):  # noqa: E501
        """LinestringGeoJSON - a model defined in OpenAPI

        :param type: The type of this LinestringGeoJSON.  # noqa: E501
        :type type: str
        :param coordinates: The coordinates of this LinestringGeoJSON.  # noqa: E501
        :type coordinates: List[List[float]]
        """
        self.openapi_types = {
            'type': str,
            'coordinates': List[List[float]]
        }

        self.attribute_map = {
            'type': 'type',
            'coordinates': 'coordinates'
        }

        self._type = type
        self._coordinates = coordinates

    @classmethod
    def from_dict(cls, dikt) -> 'LinestringGeoJSON':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The linestringGeoJSON of this LinestringGeoJSON.  # noqa: E501
        :rtype: LinestringGeoJSON
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self):
        """Gets the type of this LinestringGeoJSON.


        :return: The type of this LinestringGeoJSON.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this LinestringGeoJSON.


        :param type: The type of this LinestringGeoJSON.
        :type type: str
        """
        allowed_values = ["LineString"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def coordinates(self):
        """Gets the coordinates of this LinestringGeoJSON.


        :return: The coordinates of this LinestringGeoJSON.
        :rtype: List[List[float]]
        """
        return self._coordinates

    @coordinates.setter
    def coordinates(self, coordinates):
        """Sets the coordinates of this LinestringGeoJSON.


        :param coordinates: The coordinates of this LinestringGeoJSON.
        :type coordinates: List[List[float]]
        """
        if coordinates is None:
            raise ValueError("Invalid value for `coordinates`, must not be `None`")  # noqa: E501

        self._coordinates = coordinates
