# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class SortFilter(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, sortby=None):  # noqa: E501
        """SortFilter - a model defined in OpenAPI

        :param sortby: The sortby of this SortFilter.  # noqa: E501
        :type sortby: List[object]
        """
        self.openapi_types = {
            'sortby': List[object]
        }

        self.attribute_map = {
            'sortby': 'sortby'
        }

        self._sortby = sortby

    @classmethod
    def from_dict(cls, dikt) -> 'SortFilter':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The sortFilter of this SortFilter.  # noqa: E501
        :rtype: SortFilter
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sortby(self):
        """Gets the sortby of this SortFilter.

        An array of objects containing a property name and sort direction.   # noqa: E501

        :return: The sortby of this SortFilter.
        :rtype: List[object]
        """
        return self._sortby

    @sortby.setter
    def sortby(self, sortby):
        """Sets the sortby of this SortFilter.

        An array of objects containing a property name and sort direction.   # noqa: E501

        :param sortby: The sortby of this SortFilter.
        :type sortby: List[object]
        """

        self._sortby = sortby
